# Generated by Django 5.0.6 on 2024-05-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scholar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('birth_year', models.IntegerField(max_length=10)),
                ('death_year', models.IntegerField(max_length=10)),
            ],
        ),
    ]
