# Generated by Django 5.0.4 on 2024-12-20 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('arabic_name', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Scholar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('arabic_name', models.CharField(default='', max_length=200)),
                ('birth_year', models.IntegerField()),
                ('death_year', models.IntegerField()),
                ('arabic_birth_year', models.CharField(blank=True, max_length=200, null=True)),
                ('arabic_death_year', models.CharField(blank=True, max_length=200, null=True)),
                ('arabic_year_category', models.CharField(blank=True, max_length=200, null=True)),
                ('is_favourite', models.BooleanField(default=False)),
                ('is_on_home_page', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ScholarYearCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('arabic_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.CharField(max_length=200)),
                ('arabic_quote', models.CharField(max_length=200)),
                ('is_on_home_page', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='backend.scholar')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('arabic_name', models.CharField(default='', max_length=200)),
                ('is_favourite', models.BooleanField(default=False)),
                ('is_on_home_page', models.BooleanField(default=False)),
                ('categories', models.ManyToManyField(blank=True, related_name='books', to='backend.bookcategory')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='backend.scholar')),
            ],
        ),
        migrations.AddField(
            model_name='scholar',
            name='year_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scholars', to='backend.scholaryearcategory'),
        ),
    ]
