# Generated by Django 5.0.4 on 2024-09-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='test_field',
            field=models.CharField(default='', max_length=255),
        ),
    ]
