# Generated by Django 5.0.4 on 2025-01-04 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholar',
            name='specialized_science',
            field=models.ManyToManyField(blank=True, related_name='scholars', to='backend.bookcategory'),
        ),
        migrations.AlterField(
            model_name='book',
            name='is_favourite',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='is_on_home_page',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
