# Generated by Django 5.0.4 on 2024-05-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholar',
            name='arabic_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
