# Generated by Django 5.0.4 on 2024-09-07 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_userprofile_test_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='test_field',
        ),
    ]
