# Generated by Django 5.0.4 on 2024-05-27 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_scholar_arabic_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BookYearRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.IntegerField(default=0)),
                ('end_year', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='year',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='year_range',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='backend.bookyearrange'),
        ),
    ]
