# Generated by Django 5.0.4 on 2025-01-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_scholar_specialized_science_alter_book_is_favourite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholar',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
