# Generated by Django 5.0.4 on 2024-09-07 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_testmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
