# Generated by Django 5.0.6 on 2024-05-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='book_images/'),
        ),
        migrations.AddField(
            model_name='scholar',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='scholar_images/'),
        ),
    ]
