# Generated by Django 5.0.4 on 2024-05-27 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_bookcategory_bookyearrange_book_year_book_year_range'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='year_range',
        ),
        migrations.RemoveField(
            model_name='book',
            name='year',
        ),
        migrations.DeleteModel(
            name='BookYearRange',
        ),
    ]
