# Generated by Django 5.0.4 on 2024-05-27 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_book_year_range_remove_book_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='arabic_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arabic_books', to='backend.bookcategory'),
        ),
        migrations.AddField(
            model_name='book',
            name='arabic_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='backend.bookcategory'),
        ),
        migrations.AddField(
            model_name='bookcategory',
            name='arabic_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='scholar',
            name='arabic_birth_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scholar',
            name='arabic_death_year',
            field=models.IntegerField(default=0),
        ),
    ]
