# Generated by Django 5.0.4 on 2024-05-28 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_book_arabic_category_book_arabic_name_book_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='arabic_category',
        ),
    ]
