# Generated by Django 5.0.4 on 2025-01-05 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_book_description_alter_scholar_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='is_favourite',
        ),
        migrations.RemoveField(
            model_name='scholar',
            name='is_favourite',
        ),
    ]
