# Generated by Django 5.0.4 on 2025-01-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_remove_book_is_favourite_remove_scholar_is_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='test',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
