# Generated by Django 5.0.4 on 2024-05-30 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_remove_book_category_book_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholar',
            name='arabic_birth_year',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='scholar',
            name='arabic_death_year',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
