# Generated by Django 5.0.4 on 2024-05-30 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_scholar_arabic_birth_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholar',
            name='arabic_birth_year',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='scholar',
            name='arabic_death_year',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
