# Generated by Django 5.0.4 on 2025-01-05 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_userprofile_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='test',
            new_name='test2',
        ),
    ]
