# Generated by Django 5.0.4 on 2025-01-05 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_rename_test_userprofile_test2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='favourite_books',
            new_name='favorite_books',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='favourite_scholars',
            new_name='favorite_scholars',
        ),
    ]
