# Generated by Django 5.0.4 on 2025-01-05 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_rename_favourite_books_userprofile_favorite_books_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='favorite_books',
            new_name='favourite_books',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='favorite_scholars',
            new_name='favourite_scholars',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='test2',
        ),
    ]
