# Generated by Django 5.0.4 on 2024-05-30 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_scholaryearcategory_remove_scholar_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholar',
            name='arabic_year_category',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='scholaryearcategory',
            name='arabic_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='scholaryearcategory',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
