# Generated by Django 5.0.4 on 2024-05-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_scholar_arabic_year_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholaryearcategory',
            name='arabic_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='scholaryearcategory',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
