# Generated by Django 5.0.4 on 2024-06-03 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_favouritescholar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavouriteScholar',
        ),
    ]
