# Generated by Django 5.0.4 on 2024-06-04 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_alter_scholar_arabic_year_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='image',
            new_name='image_url',
        ),
    ]
