# Generated by Django 5.0.4 on 2024-06-04 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_rename_image_book_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='image_url',
            new_name='image',
        ),
    ]
