# Generated by Django 5.0.4 on 2024-06-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_rename_image_url_book_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('my_image', models.ImageField(blank=True, null=True, upload_to='book_images/')),
            ],
        ),
    ]
