# Generated by Django 5.0.4 on 2024-06-05 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_alter_book_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyImage',
        ),
    ]
