# Generated by Django 5.0.4 on 2024-06-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_delete_myimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image_url',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='', max_length=200, upload_to=''),
        ),
    ]
