# Generated by Django 5.0.4 on 2024-06-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_book_image_url_alter_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
