# Generated by Django 5.0.4 on 2024-06-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_alter_book_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_on_home_page',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scholar',
            name='is_on_home_page',
            field=models.BooleanField(default=False),
        ),
    ]
