# Generated by Django 5.0.4 on 2024-09-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_myuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
